/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package survcalc.view;

import survcalc.model.Points;

/**
 *
 * @author John H. Goettsche <john.h.goettsche@gmail.com>
 */
public class ViewPointList extends javax.swing.JPanel implements Observer {
    Points points;
    
    /**
     * Creates new form ViewPointList
     */
    public ViewPointList() {
        initComponents();
        points = Points.getInstance();
        points.registerOberver(this);
    }

    @Override
    public void update() {
        pointTextArea.setText(points.toString());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pointScrollPane = new javax.swing.JScrollPane();
        pointTextArea = new javax.swing.JTextArea();

        pointTextArea.setColumns(20);
        pointTextArea.setRows(5);
        pointScrollPane.setViewportView(pointTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane pointScrollPane;
    private javax.swing.JTextArea pointTextArea;
    // End of variables declaration//GEN-END:variables
}
